[package]
name = "codeguard-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
codeguard-core = { path = "../codeguard-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
roxmltree = "0.21.1"
toml = { version = "=0.8.23", default-features = false, features = ["parse"] }

semver = "=1.0.28"
